name: Azure Load Testing Workflow

on:
  push:
      branches:
        - main

env:
  AZURE_WEBAPP_NAME: "liveworkshop-lb07v2"
  LOAD_TEST_RESOURCE: "WorkshopLoadTesting-CF-LB07"
  LOAD_TEST_RESOURCE_GROUP: "workshop-cf-lb07northeurope-rg"

jobs:
  testing:
    name: Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure Load Testing
        uses: Azure/load-testing@v1.1.27
        with:
          loadTestConfigFile: 'SampleApp.yaml'
          loadTestResource: ${{ env.LOAD_TEST_RESOURCE }}
          resourceGroup: ${{ env.LOAD_TEST_RESOURCE_GROUP }}
          env: |
            [
              {
              "name": "webapp",
              "value": "${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
              }
            ]          
      
      - uses: actions/upload-artifact@v4
        with:
          name: loadTestResults
          path: ${{ github.workspace }}/loadTest
